### ISSUE TITLE
TopoJSON detection

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-file-sniff#19]
We should be able to tell if a json format file looks like topojson (vs geojson or some non-geographical json).

**Comment by GretaCB** [comment]
Looks like topojson files can get sucked into [the geojson logic](https://github.com/mapbox/mapbox-file-sniff/blob/master/index.js#L25). I'm thinking based on both the [topojson](https://github.com/topojson/topojson-specification) and [geojson](http://geojson.org/geojson-spec.html#geojson-objects) specs:

#### Check topojson first since it can only have one value for `"type"`:
```
if (head.indexOf('\"type\": \"Topology\"') !== -1){
        return callback(null, 'geojson');
    }
```

#### Then check for geojson, as long as it has the `"type"` property at all since geojson files can have a variety of values for `"type"`.
```
if (head.indexOf('\"type\":') !== -1){
        return callback(null, 'geojson');
    }
```

cc @rclark @springmeyer

**Comment by GretaCB** [comment]
Looks like topojson files can get sucked into the geojson logic. According to the [topojson](https://github.com/topojson/topojson-specification) and [geojson](http://geojson.org/geojson-spec.html) specs, each can have a variety of values for `"type"`.

Investigating ways we can differentiate with confidence.

cc @springmeyer @rclark

**Comment by GretaCB** [comment]
One idea is to check for the presence of an `arc` property to verify topojson.

**Comment by rclark** [comment]
We make a bunch of assumptions about these JSON files to prevent us from parsing the entire file. Notably, we assume that the `type` property is defined in the first ~100 characters of the file.

I would say stick to that, but check for acceptable types of GeoJSON and TopoJSON through regex matching on the header? i.e.

```js
var m = /"type":\s?"(.+?)"/.exec(head);
if (m[1] === 'Feature' || m[1] === 'GeometryCollection' || etc) return 'geojson';
if (m[1] === 'Topology' || etc) return 'topojson';
```

**Comment by GretaCB** [comment]
PR: https://github.com/mapbox/mapbox-file-sniff/pull/22
