### ISSUE TITLE
If CRS goes before Type - geojson parsing fails

### ISSUE THREAD

**Issue by akudrya** [mapbox/mapbox-file-sniff#44]
This geojson failed to be posted - https://www.dropbox.com/s/qk7rl1tc1g5bcy3/california-test-fail.geojson?dl=0

Error - File type not supported

This geojson had no problems - https://www.dropbox.com/s/j508xar9h8bn5dv/california-test-ok.geojson?dl=0

Only difference between these 2 files is in the first - ```crs``` goes before ```Type```. Since geojson is unordered format if shouldn't be a problem, right?

**Comment by mapsam** [comment]
Hey @akudrya thanks for submitting this issue - good find! I dug into the failure, and it looks like we're just checking file headers in geojson for `"type":` which also exists in the `"crs"` property. This way, when we check the value it comes back as `name` instead of a valid GeoJSON feature type.

We'll have to add a separate check in here to make sure we aren't capturing the `type` parameter of `crs` in GeoJSON.

cc @GretaCB @who8mycakes

**Comment by mapsam** [comment]
Here's a test case

```
{
  "crs": {
    "type": "name", 
    "properties": {
      "name": "urn:ogc:def:crs:OGC:1.3:CRS84"
    }
  }, 
  "type": "FeatureCollection", 
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [125.6, 10.1]
      },
      "properties": {
        "name": "Dinagat Islands"
      }
    }
  ]
}
```

**Comment by GretaCB** [comment]
Fixed and published per https://github.com/mapbox/mapbox-file-sniff/pull/45. Closing.
